name: Check Kick live

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: python -m pip install --upgrade pip requests

      - name: Run Kick check
        env:
          KICK_USER: ${{ secrets.USER }}
          DISCORD_TOKEN: ${{ secrets.TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.CHANNEL }}
          NOTIFY_WINDOW: '15'                    
        run: python check_kick.py
