name: Check Kick live
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade pip requests
      - run: python check_kick.py
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          NOTIFY_WINDOW: "5"
          RENAME_CHANNEL_ID: "1407412902973149246"
